name: Build Godot 4.x Ultra Seco

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegando o codigo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Instalando ferramentas
        run: |
          python -m pip install scons
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libasound2-dev libpulse-dev libudev-dev libfreetype6-dev

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Compilando (Agora vai ou racha)
        run: |
          scons platform=android target=template_release arch=arm64 \
          disable_3d=yes \
          module_glslang_enabled=yes \
          module_text_server_adv_enabled=no \
          module_text_server_fb_enabled=yes \
          module_navigation_enabled=no \
          module_mobile_vr_enabled=no \
          module_openxr_enabled=no \
          -j$(nproc)

      - name: Listar o que tem na pasta bin
        run: ls -R bin/

      - name: Subir o Loot (Buscando em todos os lugares)
        uses: actions/upload-artifact@v4
        with:
          name: godot4-app-leve-final
          path: bin/ # Agora vamos subir a pasta inteira, ele acha de qualquer jeito
